### ISSUE TITLE
Run website on new AWS accounts - migration

### ISSUE THREAD

**Issue by wojtekk** [copotrzebne-pl/infrastructure#24]
## Milestone 0

- [x] Prepare and test new infrastructure - DEV and PRO

## Milestone 1 - DEV

- [x] Remove `IamPolicy` from API: `convox apps params set IamPolicy= -a api-copotrzebne-pl -r copotrzebne-pl/dev`
- [x] Detach SSL certificate from Convox ALB 
- [x] Delete all existing stacks except `remote_state`
  ```bash
  make destroy env=dev stack=api-copotrzebne-pl
  make destroy env=dev stack=convox
  make destroy env=dev stack=mails
  make destroy env=dev stack=cdn
  make destroy env=dev stack=hosting_zones
  ```
- [x] Rename `hosting_zones` to `hosted_zones` - search for all occurences
- [x] Create infra for `dev.copotrzebne.pl` (without beta) - NS records will be created on an old AWS account too
  ```bash
  make apply env=dev stack=hosted_zones
  make apply env=dev stack=cdn
  ```
- [x] Change GHA pipelines
  - [x] CF ID
  - [x] Bucket name
  - [x] AWS Key
  - [x] AWS Secret `make output-raw env=pro stack=cdn name=s3_deployer_access_key_secret`
- [x] Deploy front
- [x] Continue with Infra
  ```bash
  make apply env=dev stack=convox
  make apply env=dev stack=mails
  make apply env=dev stack=api-copotrzebne-pl
  ```
- [x] Change API configuration
  - [x] Set `IamPolicy` for API: `convox apps params set IamPolicy=<IamPolicy> -a api-copotrzebne-pl -r copotrzebne-pl/dev`
  - [x] Change `HOST` env var: `convox env edit -a api-copotrzebne-pl  -r copotrzebne-pl/dev`
- [x] Deploy API
- [x] Test everything
- [x] Adjust steps for PRO if anything was missing

## Milestone 2 - PRO

- [x] Remove `IamPolicy` from API: `convox apps params set IamPolicy= -a api-copotrzebne-pl -r copotrzebne-pl/pro`
- [x] Detach SSL certificate from Convox ALB 
- [x] Delete all existing stacks except `remote_state`
  ```bash
  make destroy env=pro stack=api-copotrzebne-pl
  make destroy env=pro stack=convox
  make destroy env=pro stack=mails
  make destroy env=pro stack=cdn
  make destroy env=pro stack=hosting_zones
  ```
- [x] Delete CloudFront distributions on old AWS account used by redirects (without www)
- [x] Rename `hosting_zones` to `hosted_zones` - search for all occurences
- [x] Uncomment new values in `environments/pro/hosting_zones/config.auto.tfvars`
- [x] Create infra for `copotrzebne.pl` (without beta)
  ```bash
  make apply env=pro stack=hosted_zones
  make apply env=pro stack=cdn
  ```
- [x] Change GHA pipelines
  - [x] CF ID
  - [x] Bucket name
  - [x] AWS Key
  - [x] AWS Secret `make output-raw env=pro stack=cdn name=s3_deployer_access_key_secret`
- [x] Deploy front
- [x] Continue with Infra
  ```bash
  make apply env=pro stack=convox
  make apply env=pro stack=mails
  make apply env=pro stack=api-copotrzebne-pl
  ```
  all DNS records will be created on an old AWS account too to prepare everything
- [x] Change API configuration
  - [x] Set `IamPolicy` for API: `convox apps params set IamPolicy=<IamPolicy> -a api-copotrzebne-pl -r copotrzebne-pl/pro`
  - [x] Change `HOST` env var: `convox env edit -a api-copotrzebne-pl  -r copotrzebne-pl/pro`
- [x] Deploy API
- [x] Test everything

## Milestone 3 - DB + API 🚀 

- [x] Migrate DB
- [x] Switch old CF to new API (on Convox)

## Milestone 4 - Front 🚀 

- [x] Switch domain without `www` to new CloudFront
- [x] Switch domain with `www` to new CloudFront

## Milestone 5 - NS 🚀 

- [x] Agnieszka change NS records

## Milestone 5 - Mail 🚀 

- [x] Create Workmail
- [x] Verify workmail

**Comment by wojtekk** [comment]
NS to share with Agnieszka:

**copotrzebne.pl**

- `ns-1262.awsdns-29.org`
- `ns-1560.awsdns-03.co.uk`
- `ns-213.awsdns-26.com`
- `ns-640.awsdns-16.net`

**whatisneeded.pl**

- `ns-1416.awsdns-49.org`
- `ns-1908.awsdns-46.co.uk`
- `ns-405.awsdns-50.com`
- `ns-640.awsdns-16.net`

**shchopotribno.pl**

- `ns-1090.awsdns-08.org`
- `ns-1740.awsdns-25.co.uk`
- `ns-331.awsdns-41.com`
- `ns-874.awsdns-45.net`

**Comment by wojtekk** [comment]
Migration completed
